# Site Information
site_name: Riad's CTF Writeups
site_url: https://rador-01.github.io/CTF-Blog/
site_description: CTF writeups focusing on Network Forensics, Web Exploitation, and OSINT
site_author: Riad

# Repository
repo_name: Rador-01/CTF-Blog
repo_url: https://github.com/Rador-01/CTF-Blog

# Theme Configuration
theme:
  name: material
  palette:
    # Dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs           # Top navigation tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  font:
    text: Inter
    code: Fira Code
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/shield-lock

# Navigation Structure
nav:
  - Home: index.md
  - Writeups:
    - UofT CTF 2026:
      - Forensics: writeups/UofTCTF2026/WriteUp_Team K&K Network Forensics Challenge.md
  - About: about.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - toc:
      permalink: true

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Rador-01

# Copyright
copyright: Copyright &copy; 2026 RiadBenbrahim