# Site Information
site_name: Riad's CTF Writeups
site_url: https://rador-01.github.io/CTF-Blog/
site_description: CTF writeups focusing on Network Forensics, Web Exploitation, and OSINT
site_author: Riad

# Repository
repo_name: Rador-01/CTF-Blog
repo_url: https://github.com/Rador-01/CTF-Blog

# Theme Configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: amber
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - announce.dismiss
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/bug
    admonition:
      note: material/pencil-circle
      tip: material/fire
      warning: material/alert-octagon
      danger: material/skull-crossbones

# Navigation Structure
nav:
  - Home: index.md
  - Writeups:
    - UofT CTF 2026:
      - Forensics: writeups/UofTCTF2026/WriteUp_Team K&K Network Forensics Challenge.md
  - About: about.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - admonition
  - tables
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: "🔗"
      toc_depth: 3

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Footer & Social
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Rador-01
      name: GitHub

# Copyright
copyright: Copyright &copy; 2026 RiadBenbrahim